-- +goose Up
CREATE TABLE IF NOT EXISTS bookings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    screening_id bigint NOT NULL REFERENCES screenings(id),
    user_id bigint NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT bookings_screening_user_unique
        UNIQUE (screening_id, user_id)
);

-- +goose Down
DROP TABLE IF EXISTS bookings;